# Generated by Django 4.2.13 on 2024-07-11 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Music_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='Music_file'),
        ),
    ]
