# Generated by Django 4.2.13 on 2024-07-10 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
                ('num_pages', models.IntegerField(verbose_name='Pages')),
                ('author', models.CharField(max_length=70, verbose_name='Author')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Book_file')),
            ],
        ),
    ]
